### PR TITLE
allow broadcasting of simple rotations

### PR DESCRIPTION
**Pull request by FirefoxMetzger**
I noticed a bug in `la.quaternion_make_from_euler_angles`. If the user supplies a batch of `angles` but only rotates around a single axis (e.g. `order="x"`) then the current implementation produces an exception because it trips over the missing/implied core dimension of `angles`. This PR fixes that and makes batches of simple rotations behave like all the others.

### CODE REVIEW

**Comment by almarklein** [comment]
Nice find! Maybe we should also add a test to prevent a regression.

I found the following approach work well:
* Define a list of individual items (e.g. angles, vectors), and a matching list of expected results.
* Test that the function works for these individually, in a for-loop.
* Then turn that list into an array, and apply the function to the batch, and test that result too.

**Comment by FirefoxMetzger** [comment]
I'm always a bit cautious with loops inside a test, because it makes it difficult to set a breakpoint and jump to that line instantly while debugging (you end up stepping through the loop manually, hitting the breakpoint during each iteration).

My approach would have been to add a strategy to hypothesis that generates (broadcastable) batches of vectors and to test on these in addition to their flat counterparts.

**Comment by almarklein** [comment]
Whatever works to test both the singular and batched usage 👍

**Comment by Korijn** [comment]
> I'm always a bit cautious with loops inside a test, because it makes it difficult to set a breakpoint and jump to that line instantly while debugging (you end up stepping through the loop manually, hitting the breakpoint during each iteration).

Just as a tip if you find yourself in situations like that in the future, you can make breakpoints conditional on certain expressions.

**Review by Korijn — APPROVED** [review]

**Comment by FirefoxMetzger** [comment]
Cool. I knew I can modify the code itself and set a breakpoint inside a branch, but it never occurred to me that you can set conditions on breakpoints in IDEs. Learned something new today.

**Pull request merged**
